using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Assignment4
{
    /// <summary>
    /// Represents a product category in the Northwind database.
    /// Categories are used to group related products (e.g., Beverages, Dairy Products).
    /// </summary>
    public class Category
    {
        /// <summary>
        /// Primary key. Maps to 'categoryid' column in the database.
        /// Note: This is NOT auto-generated by the database; must be set manually
        /// before inserting (see DataService.CreateCategory for implementation).
        /// </summary>
        public int Id { get; set; }
        
        /// <summary>
        /// Category name (e.g., "Beverages", "Condiments").
        /// Maps to 'categoryname' column.
        /// </summary>
        public string Name { get; set; }
        
        /// <summary>
        /// Detailed description of the category.
        /// Maps to 'description' column.
        /// </summary>
        public string Description { get; set; }
    }
}